"""Spider2-DBT AutoResearch Loop
=================================

Autonomous prompt optimisation loop for Spider2-DBT using DSPy + MIPROv2.
Inspired by Karpathy's autoresearch (github.com/karpathy/autoresearch).

How it works
------------
1. Create a git branch  autoresearch/<tag>
2. Run baseline eval on a small dev set (~12 tasks)
3. Run MIPROv2 to propose better instructions for the DSPy module
4. Re-eval with optimised module
5. If score improved  → save, git commit, append to findings.md
   If not             → discard, append "no improvement" to findings.md
6. LOOP FOREVER until you kill it

Usage
-----
    # One-time setup: download spider2-dbt source databases first
    #   cd ~/repos/Spider2/spider2-dbt
    #   pip install gdown
    #   gdown 'https://drive.google.com/uc?id=1N3f7BSWC4foj-V-1C9n8M2XmgV7FOcqL'
    #   gdown 'https://drive.google.com/uc?id=1s0USV_iQLo4oe05QqAMnhGGp5jeejCzp'
    #   python setup.py

    uv run scripts/autoresearch_spider2.py

    # Optional flags:
    #   --run-tag  may24     (default: today, e.g. "may23")
    #   --dev-set  12        (number of tasks for fast iteration, default 12)
    #   --max-iters 0        (0 = run forever, default 0)
    #   --full-eval          (also run all 68 tasks after each keep)

Environment
-----------
    ANTHROPIC_API_KEY   required
    SPIDER2_DATA_DIR    path to Spider2 repo clone (default: ~/repos/Spider2)
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys
import textwrap
import time
from pathlib import Path

# ── repo paths ────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).parent.parent
SPIDER2_DATA_DIR = Path(
    os.environ.get("SPIDER2_DATA_DIR", Path.home() / "repos" / "Spider2")
)
SPIDER2_DBT_DIR = SPIDER2_DATA_DIR / "spider2-dbt"
AUTORESEARCH_OUTPUT = REPO_ROOT / "autoresearch_output"
FINDINGS_DIR = REPO_ROOT / "findings"
RESULTS_TSV = REPO_ROOT / "results.tsv"
OPTIMIZED_MODULE_PATH = REPO_ROOT / "src" / "labrat" / "dspy_opt" / "optimized_module.json"

FINDINGS_DIR.mkdir(exist_ok=True)
AUTORESEARCH_OUTPUT.mkdir(exist_ok=True)


# ── git helpers ───────────────────────────────────────────────────────────────


def git(*args: str) -> str:
    result = subprocess.run(["git", *args], capture_output=True, text=True, cwd=REPO_ROOT)
    return result.stdout.strip()


def git_hash() -> str:
    return git("rev-parse", "--short", "HEAD")


def git_current_branch() -> str:
    return git("rev-parse", "--abbrev-ref", "HEAD")


# ── TSV results log ───────────────────────────────────────────────────────────


def init_results_tsv() -> None:
    if not RESULTS_TSV.exists():
        RESULTS_TSV.write_text("commit\tscore\tdev_set_n\tstatus\tdescription\n")


def log_result(
    commit: str,
    score: float,
    dev_set_n: int,
    status: str,
    description: str,
) -> None:
    init_results_tsv()
    row = f"{commit}\t{score:.4f}\t{dev_set_n}\t{status}\t{description}\n"
    with RESULTS_TSV.open("a") as f:
        f.write(row)


# ── findings markdown (append-only) ──────────────────────────────────────────


FINDINGS_PATH = FINDINGS_DIR / "spider2_dbt_findings.md"


def init_findings(run_tag: str) -> None:
    if not FINDINGS_PATH.exists():
        FINDINGS_PATH.write_text(
            "# Spider2-DBT AutoResearch Findings\n\n"
            "> Append-only log generated by `scripts/autoresearch_spider2.py`.\n"
            "> Each `##` block is one run; each `###` block is one DSPy optimisation iteration.\n\n"
        )
    with FINDINGS_PATH.open("a") as f:
        f.write(
            f"\n---\n\n"
            f"## Run `{run_tag}` — {datetime.datetime.now():%Y-%m-%d %H:%M}\n\n"
        )


def _extract_instruction(module: object) -> str:
    """Pull the current signature instruction out of a DBTModelCompletion module."""
    try:
        return module.generate.predict.signature.instructions  # type: ignore[union-attr]
    except AttributeError:
        return "(could not extract instruction)"


def _task_rows(eval_result: object, prev_passing: set[str] | None) -> tuple[str, set[str]]:
    """Build a markdown task table and return the set of passing task IDs."""
    results = getattr(eval_result, "results", [])
    passing: set[str] = set()
    rows: list[str] = ["| Task | Result | Change |", "|------|--------|--------|"]
    for example, _prediction, score in results:
        tid = getattr(example, "instance_id", "?")
        ok = bool(score)
        if ok:
            passing.add(tid)
        icon = "✅" if ok else "❌"
        if prev_passing is None:
            change = "—"
        elif ok and tid not in prev_passing:
            change = "⬆ new pass"
        elif not ok and tid in prev_passing:
            change = "⬇ regression"
        else:
            change = "—"
        rows.append(f"| `{tid}` | {icon} | {change} |")
    return "\n".join(rows), passing


def append_finding(
    iteration: int,
    score: float,
    prev_score: float | None,
    status: str,
    notes: str,
    eval_result: object | None = None,
    prev_passing: set[str] | None = None,
    module: object | None = None,
    new_instruction: str | None = None,
) -> set[str]:
    """Append one iteration's findings to FINDINGS_PATH. Returns set of passing task IDs."""
    delta_str = ""
    if prev_score is not None:
        delta = score - prev_score
        delta_str = f" | **Δ** {delta:+.1%}"

    if iteration == 0:
        heading = f"### Iteration 0 — Baseline"
    else:
        heading = f"### Iteration {iteration} — MIPROv2"

    passing: set[str] = set()
    task_table = ""
    if eval_result is not None:
        task_table, passing = _task_rows(eval_result, prev_passing)

    instruction_block = ""
    if new_instruction:
        instruction_block = (
            f"\n**Updated instruction (MIPROv2 → new):**\n"
            f"```\n{new_instruction.strip()}\n```\n"
        )
    elif module is not None and iteration == 0:
        instr = _extract_instruction(module)
        instruction_block = (
            f"\n**Instruction (baseline):**\n"
            f"```\n{instr.strip()}\n```\n"
        )

    # Build new + still-failing summaries when we have task data
    summary_lines: list[str] = []
    if eval_result is not None and prev_passing is not None:
        new_pass = passing - prev_passing
        new_fail = prev_passing - passing
        if new_pass:
            summary_lines.append(f"**Newly passing:** {', '.join(f'`{t}`' for t in sorted(new_pass))}")
        if new_fail:
            summary_lines.append(f"**Regressions:** {', '.join(f'`{t}`' for t in sorted(new_fail))}")
        still_fail = {r[0].instance_id for r in getattr(eval_result, 'results', []) if not r[2]} - new_fail
        if still_fail:
            summary_lines.append(f"**Still failing ({len(still_fail)}):** {', '.join(f'`{t}`' for t in sorted(still_fail))}")

    n_tasks = len(getattr(eval_result, "results", [])) if eval_result is not None else 0
    n_pass = round(score * n_tasks) if n_tasks else round(score * 12)
    denom = n_tasks or 12
    block = (
        f"\n{heading}\n\n"
        f"**Score:** {score:.1%} ({n_pass}/{denom}){delta_str}  \n"
        f"**Status:** {status}  \n"
        f"**Notes:** {notes}\n\n"
        + (task_table + "\n\n" if task_table else "")
        + ("\n".join(summary_lines) + "\n\n" if summary_lines else "")
        + instruction_block
    )

    with FINDINGS_PATH.open("a") as f:
        f.write(block)

    return passing


# ── DSPy example loader ───────────────────────────────────────────────────────


def load_dev_set(n: int, gold_eval: dict) -> list:
    """Load the first n tasks as dspy.Example objects."""
    import dspy

    tasks_file = SPIDER2_DBT_DIR / "examples" / "spider2-dbt.jsonl"
    tasks = [json.loads(line) for line in tasks_file.read_text().splitlines() if line.strip()]

    from labrat.dspy_opt.executor import identify_target_file, load_project_files

    examples = []
    skipped = 0
    for task in tasks:
        if len(examples) >= n:
            break
        instance_id: str = task["instance_id"]
        gold_entry = gold_eval.get(instance_id)
        if not gold_entry:
            skipped += 1
            continue

        project_dir = SPIDER2_DBT_DIR / "examples" / instance_id
        if not project_dir.exists():
            skipped += 1
            continue

        # Check source DuckDB exists (requires gdown + setup.py to have been run)
        import yaml
        profiles_file = project_dir / "profiles.yml"
        if not profiles_file.exists():
            skipped += 1
            continue
        profiles = yaml.safe_load(profiles_file.read_text())
        source_db_exists = False
        for _pname, profile in profiles.items():
            for _tname, cfg in profile.get("outputs", {}).items():
                if cfg.get("type") == "duckdb":
                    # Source DuckDB should be in the project dir already
                    # (setup.py copies it there); if it's not, skip
                    db_path = project_dir / cfg["path"]
                    # The source DB is the existing one before dbt run;
                    # dbt will overwrite/create it — we just need the seed data files
                    source_db_exists = True  # assume setup.py ran correctly
        if not source_db_exists:
            skipped += 1
            continue

        params = gold_entry["evaluation"]["parameters"]
        condition_tabs: list[str] = params.get("condition_tabs", [])
        target_file = identify_target_file(project_dir, condition_tabs)
        project_files = load_project_files(project_dir)

        examples.append(
            dspy.Example(
                instance_id=instance_id,
                instruction=task["instruction"],
                project_files=project_files,
                target_file=target_file,
            ).with_inputs("instance_id", "instruction", "project_files", "target_file")
        )

    if skipped:
        print(f"  (skipped {skipped} tasks — missing source data or gold entry)")
    return examples


# ── failure examination ───────────────────────────────────────────────────────


def examine_failures(iteration: int, eval_result: object, run_tag: str) -> None:
    """Write generated SQL for each failing task to autoresearch_output/<run_tag>/failures_iterN.md."""
    output_dir = AUTORESEARCH_OUTPUT / run_tag
    output_dir.mkdir(exist_ok=True)
    output_file = output_dir / f"failures_iter{iteration}.md"

    results = getattr(eval_result, "results", [])
    lines = [f"# Failure Analysis — Iteration {iteration}\n"]
    for example, prediction, score in results:
        if score:
            continue
        tid = getattr(example, "instance_id", "?")
        instruction = getattr(example, "instruction", "")
        sql = getattr(prediction, "completed_sql", None) or "(no output)"
        lines.append(
            f"\n## `{tid}`\n\n"
            f"**Instruction:** {instruction}\n\n"
            f"**Generated SQL:**\n```sql\n{sql.strip()}\n```\n"
        )

    output_file.write_text("\n".join(lines))
    print(f"  Failure analysis → {output_file.relative_to(REPO_ROOT)}")


# ── main autoresearch loop ────────────────────────────────────────────────────


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Spider2-DBT AutoResearch Loop")
    p.add_argument("--run-tag", default=None, help="Branch suffix, e.g. 'may24' (default: today)")
    p.add_argument("--dev-set", type=int, default=12, help="Tasks in dev set (default: 12)")
    p.add_argument("--max-iters", type=int, default=0, help="0 = run forever (default: 0)")
    p.add_argument("--full-eval", action="store_true", help="Run all 68 tasks after each keep")
    p.add_argument("--threads", type=int, default=4, help="DSPy eval parallelism (default: 4)")
    p.add_argument(
        "--model", default=None,
        help="Model alias: sonnet (default), haiku, opus — or a full model ID",
    )
    p.add_argument(
        "--folds", type=int, default=4,
        help="K-fold CV: number of folds to rotate val set across (default: 4)",
    )
    p.add_argument(
        "--examine-failures", action="store_true",
        help="Write generated SQL for failing tasks to autoresearch_output/<tag>/failures_iterN.md",
    )
    p.add_argument(
        "--use-agent", action="store_true",
        help="Use Spider2AgentModule (multi-turn ReAct) instead of DSPy single-shot module",
    )
    p.add_argument(
        "--agent-max-turns", type=int, default=40,
        help="Max turns for Spider2AgentModule (default: 40)",
    )
    p.add_argument(
        "--baseline-only", action="store_true",
        help="Run baseline eval and print score, then exit (no MIPROv2 optimization)",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    # ── sanity checks ──────────────────────────────────────────────────────────

    if not (SPIDER2_DBT_DIR / "examples" / "spider2-dbt.jsonl").exists():
        sys.exit(
            f"ERROR: Spider2-DBT not found at {SPIDER2_DBT_DIR}\n"
            "Set SPIDER2_DATA_DIR to your Spider2 repo clone."
        )

    import dspy

    from labrat.dspy_opt.executor import DBTExecutor
    from labrat.dspy_opt.metric import load_gold_eval, make_metric
    from labrat.dspy_opt.module import DBTModelCompletion

    # ── setup ──────────────────────────────────────────────────────────────────

    model_slug = (args.model or "sonnet").split("/")[-1].split("-")[0]  # e.g. "haiku", "sonnet"
    default_tag = datetime.date.today().strftime("%b%d").lower()
    if args.model and args.model != "sonnet":
        default_tag = f"{default_tag}-{model_slug}"
    run_tag = args.run_tag or default_tag
    branch = f"autoresearch/{run_tag}"

    print(f"\nSpider2-DBT AutoResearch  |  branch={branch}  |  dev_set={args.dev_set}")
    print("=" * 70)

    # Create branch (skip if already on it)
    if git_current_branch() != branch:
        if git("branch", "--list", branch):
            print(f"Branch {branch} already exists — switching to it")
            subprocess.run(["git", "checkout", branch], cwd=REPO_ROOT, check=True)
        else:
            subprocess.run(["git", "checkout", "-b", branch], cwd=REPO_ROOT, check=True)
            print(f"Created branch {branch}")

    # DSPy LM — prefer claude CLI (Max subscription), fall back to API key
    from labrat.dspy_opt.claude_code_lm import ClaudeCodeLM, _SUPPORTED_MODELS
    import shutil as _shutil
    if _shutil.which("claude"):
        lm = ClaudeCodeLM(model=args.model, timeout=180, max_tokens=4096)
        resolved = _SUPPORTED_MODELS.get(args.model or "", args.model) or "claude-sonnet-4-6"
        print(f"  LM: claude CLI ({resolved})")
    elif os.environ.get("ANTHROPIC_API_KEY"):
        model_id = _SUPPORTED_MODELS.get(args.model or "sonnet", args.model) or "claude-sonnet-4-6"
        lm = dspy.LM(f"anthropic/{model_id}", max_tokens=4096)
        print(f"  LM: Anthropic API ({model_id})")
    else:
        sys.exit("ERROR: neither claude CLI nor ANTHROPIC_API_KEY available")
    dspy.configure(lm=lm)

    # Load gold eval
    gold_eval = load_gold_eval(SPIDER2_DBT_DIR)

    # Load dev set
    print(f"\nLoading dev set ({args.dev_set} tasks)…")
    dev_set = load_dev_set(args.dev_set, gold_eval)
    if not dev_set:
        sys.exit(
            "ERROR: No tasks loaded. Have you run setup.py in spider2-dbt?\n"
            "  cd ~/repos/Spider2/spider2-dbt\n"
            "  gdown 'https://drive.google.com/uc?id=1N3f7BSWC4foj-V-1C9n8M2XmgV7FOcqL'\n"
            "  gdown 'https://drive.google.com/uc?id=1s0USV_iQLo4oe05QqAMnhGGp5jeejCzp'\n"
            "  python setup.py"
        )
    print(f"  Loaded {len(dev_set)} tasks for dev set")

    # Shuffle once with a fixed seed so fold boundaries are reproducible but not
    # biased by JSONL order (playbook001 was always first → always in training).
    import random as _random
    shuffled_dev = list(dev_set)
    _random.Random(42).shuffle(shuffled_dev)
    passing_ids = [e.instance_id for e in shuffled_dev]
    print(f"  Shuffle order: {passing_ids}")

    executor = DBTExecutor(SPIDER2_DBT_DIR, AUTORESEARCH_OUTPUT / run_tag)

    if args.use_agent:
        from labrat.dspy_opt.spider2_agent import Spider2AgentModule
        from labrat.dspy_opt.metric import make_agent_metric
        module = Spider2AgentModule(
            spider2_dbt_dir=SPIDER2_DBT_DIR,
            output_base=AUTORESEARCH_OUTPUT / run_tag,
            gold_eval=gold_eval,
            max_turns=args.agent_max_turns,
        )
        metric = make_agent_metric(SPIDER2_DBT_DIR, gold_eval)
        print(f"  Mode: Spider2AgentModule (max_turns={args.agent_max_turns})")
    else:
        metric = make_metric(executor, SPIDER2_DBT_DIR, gold_eval)
        module = DBTModelCompletion()
        if OPTIMIZED_MODULE_PATH.exists():
            try:
                module.load(str(OPTIMIZED_MODULE_PATH))
                print(f"  Loaded optimised module from {OPTIMIZED_MODULE_PATH.name}")
            except Exception as e:
                print(f"  Could not load saved module ({e}), starting fresh")
        print("  Mode: DBTModelCompletion (DSPy single-shot)")

    evaluator = dspy.Evaluate(
        devset=shuffled_dev,
        metric=metric,
        num_threads=args.threads,
        display_progress=True,
        display_table=False,
    )

    # Findings log
    init_findings(run_tag)
    init_results_tsv()

    # ── baseline ───────────────────────────────────────────────────────────────

    print(f"\n[Baseline] evaluating {len(dev_set)} tasks…")
    t0 = time.monotonic()
    baseline_eval = evaluator(module)
    baseline_score: float = baseline_eval.score / 100.0
    elapsed = time.monotonic() - t0

    print(f"  Baseline score: {baseline_score:.1%}  ({elapsed:.0f}s)")
    log_result(git_hash(), baseline_score, len(dev_set), "keep", "baseline")
    prev_passing = append_finding(
        0, baseline_score, None, "baseline", f"{elapsed:.0f}s eval time",
        eval_result=baseline_eval, module=module,
    )
    if args.examine_failures:
        examine_failures(0, baseline_eval, run_tag)

    best_score = baseline_score
    best_module = module

    if args.baseline_only:
        print(f"\nBaseline-only mode — done. Score: {baseline_score:.1%}")
        return

    # ── optimisation loop ──────────────────────────────────────────────────────

    iteration = 0
    while True:
        iteration += 1
        if args.max_iters > 0 and iteration > args.max_iters:
            print(f"\nReached --max-iters {args.max_iters}. Stopping.")
            break

        k = args.folds
        fold_size = max(1, len(shuffled_dev) // k)
        fold_idx = (iteration - 1) % k
        val_start = fold_idx * fold_size
        val_end = min(val_start + fold_size, len(shuffled_dev))
        val_set = shuffled_dev[val_start:val_end]
        train_set = shuffled_dev[:val_start] + shuffled_dev[val_end:]
        val_ids = [e.instance_id for e in val_set]

        print(
            f"\n[Iteration {iteration}] running MIPROv2…  "
            f"(best so far: {best_score:.1%}, fold {fold_idx+1}/{k}, val={val_ids})"
        )

        try:
            optimizer = dspy.MIPROv2(
                metric=metric,
                auto="light",
                num_threads=args.threads,
                verbose=False,
            )
            optimized = optimizer.compile(
                best_module.deepcopy(),
                trainset=train_set,
                valset=val_set if val_set else train_set,
                requires_permission_to_run=False,
            )
        except Exception as e:
            print(f"  MIPROv2 failed: {e}")
            append_finding(iteration, best_score, best_score, "⚠️ error", str(e)[:200])
            subprocess.run(["git", "add", str(FINDINGS_PATH)], cwd=REPO_ROOT)
            subprocess.run(["git", "commit", "--allow-empty", "-m", f"findings: iter {iteration} error"], cwd=REPO_ROOT)
            continue

        new_instruction = _extract_instruction(optimized)

        print(f"  Evaluating optimised module…")
        t0 = time.monotonic()
        new_eval = evaluator(optimized)
        new_score: float = new_eval.score / 100.0
        elapsed = time.monotonic() - t0
        delta = new_score - best_score

        print(f"  Score: {new_score:.1%}  (delta: {delta:+.1%},  {elapsed:.0f}s)")

        if args.examine_failures:
            examine_failures(iteration, new_eval, run_tag)

        if new_score > best_score:
            optimized.save(str(OPTIMIZED_MODULE_PATH))
            prev_passing = append_finding(
                iteration, new_score, best_score, "✅ keep",
                f"eval {elapsed:.0f}s",
                eval_result=new_eval,
                prev_passing=prev_passing,
                new_instruction=new_instruction,
            )
            subprocess.run(
                ["git", "add", str(OPTIMIZED_MODULE_PATH), str(FINDINGS_PATH)],
                cwd=REPO_ROOT,
            )
            commit_msg = (
                f"autoresearch/{run_tag} iter {iteration}: "
                f"{new_score:.1%} ({delta:+.1%})\n\n"
                f"Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
            )
            subprocess.run(["git", "commit", "-m", commit_msg], cwd=REPO_ROOT)
            log_result(git_hash(), new_score, len(dev_set), "keep", f"MIPROv2 iter {iteration}")

            best_score = new_score
            best_module = optimized

            if args.full_eval:
                _run_full_eval(module=optimized, gold_eval=gold_eval, executor=executor, metric=metric)
        else:
            append_finding(
                iteration, new_score, best_score, "❌ discard",
                f"eval {elapsed:.0f}s",
                eval_result=new_eval,
                prev_passing=prev_passing,
                new_instruction=new_instruction,
            )
            log_result(git_hash(), new_score, len(dev_set), "discard", f"MIPROv2 iter {iteration}")

        # Always commit findings so the log is tracked even on discard
        subprocess.run(["git", "add", str(FINDINGS_PATH)], cwd=REPO_ROOT)
        subprocess.run(
            ["git", "commit", "--allow-empty", "-m",
             f"findings: iter {iteration} {'keep' if new_score > best_score else 'discard'}"],
            cwd=REPO_ROOT,
        )


def _run_full_eval(module, gold_eval, executor, metric) -> None:
    """Run all 68 tasks and print the score. Called after a keep."""
    import dspy

    from labrat.dspy_opt.executor import identify_target_file, load_project_files

    tasks_file = SPIDER2_DBT_DIR / "examples" / "spider2-dbt.jsonl"
    tasks = [json.loads(line) for line in tasks_file.read_text().splitlines() if line.strip()]
    all_examples = []
    for task in tasks:
        iid = task["instance_id"]
        gold_entry = gold_eval.get(iid)
        if not gold_entry:
            continue
        project_dir = SPIDER2_DBT_DIR / "examples" / iid
        if not project_dir.exists():
            continue
        params = gold_entry["evaluation"]["parameters"]
        condition_tabs = params.get("condition_tabs", [])
        all_examples.append(
            dspy.Example(
                instance_id=iid,
                instruction=task["instruction"],
                project_files=load_project_files(project_dir),
                target_file=identify_target_file(project_dir, condition_tabs),
            ).with_inputs("instruction", "project_files", "target_file")
        )

    full_evaluator = dspy.Evaluate(
        devset=all_examples,
        metric=metric,
        num_threads=4,
        display_progress=True,
        display_table=False,
    )
    full_score: float = full_evaluator(module).score / 100.0
    print(f"\n  [Full eval — all {len(all_examples)} tasks] score: {full_score:.1%}")
    log_result(git_hash(), full_score, len(all_examples), "keep", "full eval")
    append_finding(-1, full_score, None, "full eval", f"{len(all_examples)} tasks")


if __name__ == "__main__":
    main()
