"""HTML export for pinned findings (M20).

Generates a self-contained HTML report (no external assets) from a list of
Finding objects. The template is embedded so no file lookup is needed.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment

from labrat.thread.model import Finding

_TEMPLATE_SRC = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LabRat Report — {{ timestamp }}</title>
  <style>
    /* self-contained styles — no external assets */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a2e;
      background: #f5f5f5;
      padding: 2rem;
    }
    .header {
      max-width: 900px;
      margin: 0 auto 2rem;
      padding-bottom: 1rem;
      border-bottom: 2px solid #4a4e69;
    }
    .header h1 { font-size: 1.8rem; color: #4a4e69; }
    .header .meta { color: #6c757d; font-size: 0.9rem; margin-top: 0.25rem; }
    .finding {
      background: #fff;
      border-radius: 8px;
      box-shadow: 0 1px 4px rgba(0,0,0,.1);
      padding: 1.5rem;
      max-width: 900px;
      margin: 0 auto 1.5rem;
    }
    .finding-number {
      font-size: 0.8rem;
      color: #6c757d;
      text-transform: uppercase;
      letter-spacing: .05em;
      margin-bottom: 0.5rem;
    }
    .question { font-size: 1.2rem; font-weight: 600; margin-bottom: 1rem; }
    .note {
      background: #fffbeb;
      border-left: 3px solid #f59e0b;
      padding: 0.5rem 1rem;
      margin-bottom: 1rem;
      font-style: italic;
      color: #78350f;
    }
    .sql-block {
      background: #1e1e2e;
      color: #cdd6f4;
      border-radius: 6px;
      padding: 1rem 1.25rem;
      overflow-x: auto;
      font-family: "SF Mono", "Fira Code", Consolas, monospace;
      font-size: 0.88rem;
      margin-bottom: 1rem;
    }
    .meta-row {
      font-size: 0.82rem;
      color: #6c757d;
      margin-top: 0.5rem;
    }
    .footer {
      max-width: 900px;
      margin: 2rem auto 0;
      text-align: center;
      font-size: 0.8rem;
      color: #adb5bd;
    }
    .empty-state {
      max-width: 900px;
      margin: 4rem auto;
      text-align: center;
      color: #6c757d;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>LabRat Report</h1>
    <div class="meta">
      Generated {{ timestamp }} &nbsp;|&nbsp;
      {{ finding_count }} finding{{ "s" if finding_count != 1 else "" }}
    </div>
  </div>

  {% if findings %}
    {% for f in findings %}
    <div class="finding">
      <div class="finding-number">Finding {{ loop.index }} of {{ findings | length }}</div>
      <div class="question">{{ f.question | e }}</div>
      {% if f.note %}
      <div class="note">{{ f.note | e }}</div>
      {% endif %}
      <div class="sql-block"><pre>{{ f.sql | e }}</pre></div>
      <div class="meta-row">Pinned {{ f.pinned_at.strftime("%Y-%m-%d %H:%M UTC") }}</div>
    </div>
    {% endfor %}
  {% else %}
  <div class="empty-state">
    <p>No findings to display.</p>
  </div>
  {% endif %}

  <div class="footer">
    Generated by <strong>LabRat</strong> &mdash; terminal-native data agent
  </div>
</body>
</html>
"""

_ENV = Environment(autoescape=False)  # we escape manually in the template with | e
_TMPL = _ENV.from_string(_TEMPLATE_SRC)


def export_findings(
    findings: list[Finding],
    output_dir: Path | None = None,
    title: str = "LabRat Report",
) -> Path:
    """Render findings as a self-contained HTML file and return its path.

    The file is written to ``output_dir`` (default: system temp dir) with a
    unique filename so successive exports never overwrite each other.
    """
    if output_dir is None:
        import tempfile

        output_dir = Path(tempfile.gettempdir())

    output_dir.mkdir(parents=True, exist_ok=True)
    filename = f"labrat_report_{uuid.uuid4().hex[:8]}.html"
    out = output_dir / filename

    ctx: dict[str, Any] = {
        "findings": findings,
        "finding_count": len(findings),
        "timestamp": datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC"),
        "title": title,
    }
    out.write_text(_TMPL.render(**ctx), encoding="utf-8")
    return out
