"""tui_first_connect_prepass: generate-once, reuse, staleness detection."""

from pathlib import Path

from labrat.db.duckdb_engine import DuckDBConnection
from labrat.maze.first_connect import tui_first_connect_prepass
from labrat.maze.staleness import read_scent_fingerprint, write_scent_fingerprint


def _connect(db_path: Path) -> tuple[DuckDBConnection, object]:
    conn = DuckDBConnection(path=str(db_path), read_only=True)
    conn.connect()
    return conn, conn.introspect_catalog()


async def test_first_contact_generates_docs_and_sidecar(ecommerce_db: Path, tmp_path: Path) -> None:
    conn, catalog = _connect(ecommerce_db)
    scent_dir = tmp_path / "scent"
    outcome = await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    assert outcome.generated is True
    assert outcome.stale is False
    assert len(outcome.doc_paths) >= 1
    assert all(p.suffix == ".md" for p in outcome.doc_paths)
    assert read_scent_fingerprint(scent_dir) is not None


async def test_second_connect_reuses_and_is_fresh(ecommerce_db: Path, tmp_path: Path) -> None:
    conn, catalog = _connect(ecommerce_db)
    scent_dir = tmp_path / "scent"
    first = await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    second = await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    assert second.generated is False
    assert second.stale is False
    assert set(second.doc_paths) == set(first.doc_paths)


async def test_stale_when_fingerprint_mismatches(ecommerce_db: Path, tmp_path: Path) -> None:
    conn, catalog = _connect(ecommerce_db)
    scent_dir = tmp_path / "scent"
    await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    write_scent_fingerprint(scent_dir, "stale-fingerprint")  # simulate schema drift
    outcome = await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    assert outcome.generated is False
    assert outcome.stale is True


async def test_missing_sidecar_on_existing_docs_is_not_stale(
    ecommerce_db: Path, tmp_path: Path
) -> None:
    # Docs generated by older tooling without a sidecar: is_stale(None, ...) is False.
    conn, catalog = _connect(ecommerce_db)
    scent_dir = tmp_path / "scent"
    await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    (scent_dir / ".schema_fingerprint").unlink()
    outcome = await tui_first_connect_prepass(
        connections={"main": conn},
        catalogs={"main": catalog},
        primary="main",
        catalog=catalog,
        scent_dir=scent_dir,
    )
    assert outcome.stale is False
